openapi: 3.0.0
info:
  title: API de Produtos
  version: 1.0.0
paths:
  /produtos:
    get:
      summary: Lista todos os produtos
      responses:
        '200':
          description: Lista de produtos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    nome:
                      type: string
                    preco:
                      type: number
